---
title: "Righting Response Curves"
author: "Kevin Mack"
date: "3/2/2016"
output: html_document
---
```{r, echo=F}
KM_Righting <- read.csv("~/Incubation Analysis/Trial1_sublethal.csv")
library(survival)


#this will be for making pretty curves
BlyCreek=subset(KM_Righting, Site =="Bly Creek")
TownCreek=subset(KM_Righting, Site =="Town Creek")
Grice=subset(KM_Righting, Site =="Grice")
Bowens=subset(KM_Righting, Site =="Bowens Island")
Trask=subset(KM_Righting, Site =="Trask")
Pinckney=subset(KM_Righting, Site =="Pinckney")
ExOffice=subset(KM_Righting, Site =="Extension Office")
RobHouse=subset(KM_Righting, Site =="Roebling House")
Baruch=subset(KM_Righting, Location == "Baruch")
Charleston=subset(KM_Righting, Location == "Charleston")
HiltonHead=subset(KM_Righting, Location == "Hilton Head")
Savannah=subset(KM_Righting, Location == "Savannah")
North=subset(KM_Righting, Region == "North")
South=subset(KM_Righting, Region == "South")
Male=subset(KM_Righting, Sex =="Male")
Female=subset(KM_Righting, Sex =="Female")


bc=survfit(Surv(Duration[Site=="Bly Creek"], Status[Site=="Bly Creek"])~1, data=KM_Righting)
tc=survfit(Surv(Duration[Site=="Town Creek"], Status[Site=="Town Creek"])~1, data=KM_Righting)
grice=survfit(Surv(Duration[Site=="Grice"], Status[Site=="Grice"])~1, data=KM_Righting)
bowens=survfit(Surv(Duration[Site=="Bowens Island"], Status[Site=="Bowens Island"])~1, data=KM_Righting)
trask=survfit(Surv(Duration[Site=="Trask"], Status[Site=="Trask"])~1, data=KM_Righting)
pinckney=survfit(Surv(Duration[Site=="Pinckney"], Status[Site=="Pinckney"])~1, data=KM_Righting)
mex=survfit(Surv(Duration[Site=="Extension Office"], Status[Site=="Extension Office"])~1, data=KM_Righting)
rh=survfit(Surv(Duration[Site=="Roebling House"], Status[Site=="Roebling House"])~1, data=KM_Righting)
baruch=survfit(Surv(Duration[Location == "Baruch"], Status[Location == "Baruch"])~1, data=KM_Righting)
chareleston=survfit(Surv(Duration[Location == "Charleston"], Status[Location == "Charleston"])~1, data=KM_Righting)
hilton=survfit(Surv(Duration[Location == "Hilton Head"], Status[Location == "Hilton Head"])~1, data=KM_Righting)
sav=survfit(Surv(Duration[Location == "Savannah"], Status[Location == "Savannah"])~1, data=KM_Righting)
north = survfit(Surv(Duration[Region == "North"], Status[Region == "North"])~1, data=KM_Righting)
south = survfit(Surv(Duration[Region == "South"], Status[Region == "South"])~1, data=KM_Righting)
male=survfit(Surv(Duration[Sex=="Male"], Status[Sex=="Male"])~1, data=KM_Righting)
female=survfit(Surv(Duration[Sex=="Female"], Status[Sex=="Female"])~1, data=KM_Righting)

bc_f=survfit(Surv(Duration[Site=="Bly Creek"], Status[Site=="Bly Creek"])~1, data=Female)
tc_f=survfit(Surv(Duration[Site=="Town Creek"], Status[Site=="Town Creek"])~1, data=Female)
grice_f=survfit(Surv(Duration[Site=="Grice"], Status[Site=="Grice"])~1, data=Female)
bowens_f=survfit(Surv(Duration[Site=="Bowens Island"], Status[Site=="Bowens Island"])~1, data=Female)
trask_f=survfit(Surv(Duration[Site=="Trask"], Status[Site=="Trask"])~1, data=Female)
pinckney_f=survfit(Surv(Duration[Site=="Pinckney"], Status[Site=="Pinckney"])~1, data=Female)
mex_f=survfit(Surv(Duration[Site=="Extension Office"], Status[Site=="Extension Office"])~1, data=Female)
rh_f=survfit(Surv(Duration[Site=="Roebling House"], Status[Site=="Roebling House"])~1, data=Female)

bc_m=survfit(Surv(Duration[Site=="Bly Creek"], Status[Site=="Bly Creek"])~1, data=Male)
tc_m=survfit(Surv(Duration[Site=="Town Creek"], Status[Site=="Town Creek"])~1, data=Male)
grice_m=survfit(Surv(Duration[Site=="Grice"], Status[Site=="Grice"])~1, data=Male)
bowens_m=survfit(Surv(Duration[Site=="Bowens Island"], Status[Site=="Bowens Island"])~1, data=Male)
trask_m=survfit(Surv(Duration[Site=="Trask"], Status[Site=="Trask"])~1, data=Male)
pinckney_m=survfit(Surv(Duration[Site=="Pinckney"], Status[Site=="Pinckney"])~1, data=Male)
mex_m=survfit(Surv(Duration[Site=="Extension Office"], Status[Site=="Extension Office"])~1, data=Male)
rh_m=survfit(Surv(Duration[Site=="Roebling House"], Status[Site=="Roebling House"])~1, data=Male)

temps=c(12,11,10,9,8,7,6)
days=c(0,24,48,72,96,120,144)

```

```{r , echo=F}
#SUBLETHAL FIGS
#SITE
par(pin=c(8.44,5.93), mai=c(1.3,1.3,1.5,0.4), oma=c(0,0,0,0))
plot(bc,conf.int='none', col = 'dodgerblue3', lwd=3, lty=c(1), cex.axis=1.5, xlab ='Time (hours)', ylab = 'Righting Probability', cex.lab=2)
mtext("Temperature",3,line=4,at=60, cex=2)
axis(3,days, labels=temps,line=1)
lines(tc,conf.int='none', col = 'dodgerblue3', lwd=3, lty=c(1))
lines(grice,conf.int='none', col = 'deepskyblue1', lwd=3, lty=c(1))
lines(bowens,conf.int='none', col = 'deepskyblue1', lwd=3, lty=c(1))
lines(trask,conf.int='none', col = 'red', lwd=3, lty=c(1))
lines(pinckney,conf.int='none', col = 'red',lwd=3, lty=c(1))
lines(mex,conf.int='none', col = 'firebrick4',lwd=3, lty=c(1))
lines(rh,conf.int='none', col = 'firebrick4',lwd=3, lty=c(1))
legend(x='bottomleft',c('Baruch', 'Charleston','Bluffton','Savannah'), col=c('dodgerblue3', 'deepskyblue1','red', 'firebrick4'),lwd=3, lty=c(1,1,1,1),cex=1.5)

#REGION
plot(north, conf.int='none', col='dodgerblue3', lwd=3, lty=c(1), cex.axis=1.5, xlab='Time (hours)', ylab = 'Righting Probability', cex.lab=2)
mtext("Temperature",3,line=4,at=60, cex=2)
axis(3,days, labels=temps,line=1)
lines(south,conf.int='none', col='firebrick4', lwd=3, lty=c(2) )
legend(x='bottomleft',c('North', 'South'),col= c('dodgerblue3','firebrick4'),lwd=3,lty=c(1,2),cex=1.5)

#SEX
 plot(male,conf.int='none', col = 'black', lty=c(3), cex.axis=1.5, lwd=3, xlab =
'Time (hours)', ylab = 'Righting Probability', cex.lab=2)
mtext("Temperature",3,line=4,at=60, cex=2)
axis(3,days, labels=temps,line=1)
 lines(female,conf.int='none', col = 'black', lwd=3, lty=c(1))
legend(x='bottomleft',c('Females', 'Males'),col='black',lwd=3,lty=c(1,3),cex=1.5)

#Females
plot(bc_f,conf.int='none', col='dodgerblue3', lty=c(1), cex.axis=1.5, lwd=3, xlab ='Time (hours)', ylab = 'Righting Probability', cex.lab=2)
mtext("Temperature",3,line=4,at=60, cex=2)
axis(3,days, labels=temps,line=1)
lines(tc_f,conf.int='none', col = 'dodgerblue3', lty=c(1), lwd=3)
lines(grice_f,conf.int='none', col = 'deepskyblue1', lty=c(1), lwd=3)
lines(bowens_f,conf.int='none', col = 'deepskyblue1', lty=c(1), lwd=3)
lines(trask_f,conf.int='none', col = 'red', lty=c(2), lwd=3)
lines(pinckney_f,conf.int='none', col = 'red', lty=c(2), lwd=3)
lines(mex_f,conf.int='none', col = 'firebrick4', lty=c(2), lwd=3)
lines(rh_f,conf.int='none', col = 'firebrick4', lty=c(2), lwd=3)
legend(x='bottomleft',c('Baruch: Bly Creek', 'Baruch: Town Creek','Charleston: Grice','Charleston: Bowens Island','Bluffton: Trask','Bluffton: Pinckney','Savannah: Extension Office','Savannah: Roebling House'),col=c('dodgerblue3','dodgerblue3','deepskyblue1','deepskyblue1','red','red','firebrick4','firebrick4'),lwd=3, lty=c(1,1,1,1,2,2,2,2),cex=1.5)

#Males
plot(bc_m,conf.int='none', col='dodgerblue3', lty=c(1), lwd=3, cex.axis=1.5, xlab ='Time (hours)', ylab = 'Survival Probability', cex.lab=2)
mtext("Temperature",3,line=4,at=60, cex=2)
axis(3,days, labels=temps,line=1)
lines(tc_m,conf.int='none', col = 'dodgerblue3', lty=c(1), lwd=3)
lines(grice_m,conf.int='none', col = 'deepskyblue1', lty=c(1), lwd=3)
lines(bowens_m,conf.int='none', col = 'deepskyblue1', lty=c(1), lwd=3)
lines(trask_m,conf.int='none', col = 'red', lty=c(2), lwd=3)
lines(pinckney_m,conf.int='none', col = 'red', lty=c(2), lwd=3)
lines(mex_m,conf.int='none', col = 'firebrick4', lty=c(2), lwd=3)
lines(rh_m,conf.int='none', col = 'firebrick4', lty=c(2), lwd=3)
legend(x='bottomleft',c('Baruch: Bly Creek', 'Baruch: Town Creek','Charleston: Grice','Charleston: Bowens Island','Bluffton: Trask','Bluffton: Pinckney','Savannah: Extension Office','Savannah: Roebling House'),col=c('dodgerblue3','dodgerblue3','deepskyblue1','deepskyblue1','red','red','firebrick4','firebrick4'),lwd=3, lty=c(1,1,1,1,2,2,2,2),cex=1.5)

#sexes by Region
north_sex=survfit(Surv(Duration, Status)~Sex, data=North)
south_sex=survfit(Surv(Duration, Status)~Sex, data=South)
plot(north_sex, col= c('dodgerblue3'), lty=c(1,3), lwd=3, cex.axis=1.5, xlab='Time (hours)', ylab = 'Survival Probability', cex.lab=2)
mtext("Temperature",3,line=4,at=60, cex=2)
axis(3,days, labels=temps,line=1)
lines(south_sex, col= c('firebrick4'), lty=c(1,3), lwd=3)
legend(x='bottomleft',c('North: Female', 'North: Male', 'South: Female', 'South: Male'),col= c('dodgerblue3', 'dodgerblue3', 'firebrick4', 'firebrick4'),lwd=3,lty=c(1,3,1,3),cex=1.5)

#Size
par(pin=c(8.44,5.93), mai=c(1.3,1.3,0.4,0.4), oma=c(0,0,0,0))
plot(CW~Duration, data = Male, cex.axis=1.5, xlab='Time (hours)', ylab = 'Carapace Width (mm)', cex.lab=2 )
abline(lm(CW~Duration, data=Male), , lty=c(3), lwd=3)
points(CW~Duration, data=Female, pch=19)
abline(lm(CW~Duration, data=Female), , lty=c(1), lwd=3)
legend(x='topleft',c('Female', 'Male'),lwd=3,lty=c(1,3),pch=c(19,1),cex=1.5)
```

