---
title: "Righting Response Figures"
author: "Kevin Mack"
date: "4/4/2016"
output: pdf_document
---
```{r,echo=F}
KM_Righting <- read.csv("~/Applied Quant Project/Righting-Response/Trial1_sublethal.csv")
library(survival)

#loop for sites
sites = unique(KM_Righting$Site)
mod_sites = list()
for(i in seq_along(sites)) {
  mod_sites[[i]] = survfit(Surv(Duration[Site == sites[i]], Status[Site == sites[i]]) ~ 1, data=KM_Righting)
}

#loop for region
region = unique(KM_Righting$Region)
mod_region = list()
for(i in seq_along(region)) {
  mod_region[[i]] = survfit(Surv(Duration[Region == region[i]], Status[Region == region[i]]) ~ 1, data=KM_Righting)
}

#loop for sex
sex = unique(KM_Righting$Sex)
mod_sex = list()
for(i in seq_along(sex)) {
  mod_sex[[i]] = survfit(Surv(Duration[Sex == sex[i]], Status[Sex == sex[i]]) ~ 1, data = KM_Righting)
}

#Subset sex by region
North=subset(KM_Righting, Region == "North")
South=subset(KM_Righting, Region == "South")
north_sex=survfit(Surv(Duration, Status)~Sex, data=North)
south_sex=survfit(Surv(Duration, Status)~Sex, data=South)

#Subset sex by size
Male=subset(KM_Righting, Sex =="Male")
Female=subset(KM_Righting, Sex =="Female")
```

Figure 6: Sublethal Site
```{r,echo=F}
palette(c('dodgerblue3','dodgerblue3', 'deepskyblue1', 'deepskyblue1', 'red', 'firebrick4', 'firebrick4', 'red'))
plot(mod_sites[[1]],conf.int='none', xlab ='Time (hours)', ylab = 'Survival Probability', lwd=3)
for(i in seq_along(mod_sites))
  lines(mod_sites[[i]],conf.int='none', col = i, lwd=3) 
legend(x='bottomleft',c('Baruch', 'Charleston','Bluffton','Savannah'), col=c('dodgerblue3', 'deepskyblue1','red', 'firebrick4'),lwd=3, lty=c(1,1,1,1))
```

Figure 7: Sublethal Region
```{r,echo=F}
plot(mod_region[[1]],conf.int='none', xlab ='Time (hours)', ylab = 'Survival Probability', col='dodgerblue3', lwd=3)
lines(mod_region[[2]],conf.int='none',col='firebrick4', lwd=3) 
legend(x='bottomleft',c('North', 'South'),col= c('dodgerblue3','firebrick4'),lwd=3,lty=c(1,1))
```

Figure 8: Sublethal Sex
```{r,echo=F}
plot(mod_sex[[1]],conf.int='none', xlab ='Time (hours)', ylab = 'Survival Probability', lwd=3, col='black', lty=3 )
lines(mod_sex[[2]],conf.int='none', col = 'black', lwd=3, lty = 1) 
legend(x='bottomleft',c('Females', 'Males'),col='black',lwd=3,lty=c(1,3))
```

Figure 9: Sublethal Sex by Region
```{r,echo=F}
plot(north_sex, col= c('dodgerblue3'), lty=c(1,3), lwd=3, xlab='Time (hours)', ylab = 'Survival Probability')
lines(south_sex, col= c('firebrick4'), lty=c(1,3), lwd=3)
legend(x='bottomleft',c('North: Female', 'North: Male', 'South: Female', 'South: Male'),col= c('dodgerblue3', 'dodgerblue3', 'firebrick4', 'firebrick4'),lwd=3,lty=c(1,3,1,3))
```

Figure 10: Size
```{r,echo=F, tidy=T}
plot(CW~Duration, data = Male, cex.axis=1.25, xlab='Time (hours)', ylab = 'Carapace Width (mm)')
abline(lm(CW~Duration, data=Male), , lty=c(3), lwd=2)
points(CW~Duration, data=Female, pch=19)
abline(lm(CW~Duration, data=Female), , lty=c(1), lwd=2)
legend(x='bottomleft',c('Female', 'Male'),lwd=2,lty=c(1,3),pch=c(19,1))
```

