---
title: "Presentation Analysis"
author: "Kevin Mack"
date: "3/2/2016"
output: word_document
---
```{r, echo=F}
KM_Survival <- read.csv("~/Incubation Analysis/Trial1_survival.csv")
KM_Righting <- read.csv("~/Incubation Analysis/Trial1_sublethal.csv")
KM_Survival$Block=as.factor(KM_Survival$Block)
KM_Righting$Block=as.factor(KM_Righting$Block)
library(survival)
```


Figure 1: Lethal Site
```{r, echo=F}
#Log Rank
survdiff(Surv(Duration,Status)~Block+Site, data=KM_Survival)
#Cox proportional hazards model fit
summary(coxph(Surv(Duration,Status)~Block+Site, data=KM_Survival))
#ANCOVA
anova(coxph(Surv(Duration,Status)~Block+Site, data=KM_Survival))
```

Figure 2: Lethal Region
```{r, echo=F}
#Log Rank
survdiff(Surv(Duration,Status)~Block+Region, data=KM_Survival)
#Cox proportional hazards model fit
summary(coxph(Surv(Duration,Status)~Block+Region, data=KM_Survival))
#ANOVA
anova(coxph(Surv(Duration,Status)~Block+Region, data=KM_Survival))
```

Figure 3: Lethal Sex
```{r, echo=F}
#Log Rank
survdiff(Surv(Duration,Status)~Block+Sex, data=KM_Survival)
#Cox proportional hazards model fit
summary(coxph(Surv(Duration,Status)~Block+Sex, data=KM_Survival))
#ANOVA
anova(coxph(Surv(Duration,Status)~Block+Sex, data=KM_Survival))
```

Figure 4: Lethal Sex by Region
```{r, echo=F}
#Log Rank
survdiff(Surv(Duration,Status)~Block+Sex+Region, data=KM_Survival)
#Cox proportional hazards model fit
summary(coxph(Surv(Duration,Status)~Block+Sex+Region, data=KM_Survival))
#ANOVA
anova(coxph(Surv(Duration,Status)~Block+Sex+Region, data=KM_Survival))
```

Figure 5: Lethal Size Regression
```{r, echo=F}
#subset
lethal_males=subset(KM_Survival, Sex == 'Male')
lethal_females=subset(KM_Survival, Sex == 'Female')

#Regression
summary(lm(CW~Duration, data=lethal_males))
summary(lm(CW~Duration, data=lethal_females))
```

Figure 6: Sublethal Site
```{r, echo=F}
#Log Rank test 
survdiff(Surv(Duration,Status)~Block+Site, data=KM_Righting)
#Cox proportional hazards model fit
summary(coxph(Surv(Duration,Status)~Block+Site, data=KM_Righting))
#ANCOVA of main effects 
anova(coxph(Surv(Duration,Status)~Block+Site, data=KM_Righting))

```

Figure 7: Sublethal Region
```{r, echo=F}
#Log Rank test 
survdiff(Surv(Duration,Status)~Block+Region, data=KM_Righting)
#Cox proportional hazards model fit
summary(coxph(Surv(Duration,Status)~Block+Region, data=KM_Righting))
#ANCOVA of main effects 
anova(coxph(Surv(Duration,Status)~Block+Region, data=KM_Righting))
```

Figure 8: Sublethal Sex
```{r, echo=F}
#Log Rank test 
survdiff(Surv(Duration,Status)~Block+Sex, data=KM_Righting)
#Cox proportional hazards model fit
summary(coxph(Surv(Duration,Status)~Block+Sex, data=KM_Righting))
#ANCOVA of main effects 
anova(coxph(Surv(Duration,Status)~Block+Sex, data=KM_Righting))
```

Figure 9: Sublethal Sex by Region
```{r, echo=F}
#Log Rank
survdiff(Surv(Duration,Status)~Block+Sex+Region, data=KM_Righting)
#Cox proportional hazards model fit
summary(coxph(Surv(Duration,Status)~Block+Sex+Region, data=KM_Righting))
#ANOVA
anova(coxph(Surv(Duration,Status)~Block+Sex+Region, data=KM_Righting))
```

Figure 10: Sublethal Size Regression
```{r, echo=F}
#subset
lethal_males=subset(KM_Righting, Sex == 'Male')
lethal_females=subset(KM_Righting, Sex == 'Female')

#Regression
summary(lm(CW~Duration, data=lethal_males))
summary(lm(CW~Duration, data=lethal_females))
```
